# Generated by Django 3.0.9 on 2021-10-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_photo',
            field=models.ImageField(default=False, upload_to='feature_image'),
        ),
    ]
